name: Config Workflow
description: Workflow to reconcile production config.
inputs:
  client-id:
    description: The Jira project id for the client(Use uppercase).
  repo:
    description: Repository name with owner. (owner/repo)
    default: ${{ github.repository }}
  head:
    description: Head branch to merge.
    default: ${{ github.ref }}
  base:
    description: Base branch to merge into.
    default: ${{ github.event.repository.default_branch }}
  labels:
    description: A comma seperated list of labels to add to the pull request.
    default: "prod auto pr"
  jira-url:
    description: Base URL the Jira instance.
    default: "https://discoverygarden.atlassian.net/"
  jira-user:
    description: Email of the Jira API user.
    required: true
  jira-token:
    description: API token of the Jira API user.
    required: true
  github-token:
    description: GitHub access token
    default: ${{ github.token }}
  slack-webhook:
    description: Optional Slack webhook URL to receive notifications.
    required: true

runs:
  using: composite
  steps:
    - name: Create Pull Request
      id: create_pr
      uses: discoverygarden/create-pr@v1
      with:
        title: Prod reconcile
        repo: ${{ inputs.repo }}
        head: ${{ inputs.head }}
        base: ${{ inputs.base }}
        labels: ${{ inputs.labels }}
        automerge: true
        token: ${{ inputs.github-token }}

    - name: Notify of Unmergeable Config
      if: ${{ failure() }}
      uses: discoverygarden/create-issue@v1
      with:
        project: ${{ inputs.client-id }}
        summary: Config Pull Request Failed
        description: |
          A merge conflict was found in the pull request for ${{ steps.create_pr.outputs.url }}
        transition: "To Do"
        deployment-instructions: Deploy reconciled config.
        pull-url: ${{ steps.create_pr.outputs.url }}
        jira-url: ${{ inputs.jira-url }}
        jira-user: ${{ inputs.jira-user }}
        jira-token: ${{ inputs.jira-token }}
        slack-webhook: ${{ inputs.slack-webhook }}


